version: 2.1

commands:
  setup-automation:
    steps:
      - run:
          name: Setup automation
          command: |
            (mkdir -p deps; cd deps; git clone https://github.com/RedisLabsModules/readies.git)
            FORCE=1 ./deps/readies/bin/getpy3

  build-steps:
    parameters:
      coverage:
        type: boolean
        default: false 
    steps: 
      - checkout
      - setup-automation   
      - restore_cache: # Download and cache dependencies
          keys:
          - v2-dependencies-{{ checksum "test-requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m virtualenv venv
            . venv/bin/activate
            python3 -m pip install -r test-requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "test-requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            nosetests --with-coverage -vsx test
            codecov
      
jobs:
  build:
    docker:
      # - image: debian:buster
      - image: redislabs/redisai:edge-cpu
    working_directory: ~/repo
    steps:
      - build-steps:
          coverage: true
      - store_artifacts:
          path: test-reports
          destination: test-reports

  build_nightly:
    docker:
      # - image: circleci/python:3.6.9
      - image: redislabs/redisai:edge-cpu
    working_directory: ~/repo
    steps:
      - build-steps:
          coverage: false


workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_nightly
