version: 2.1

commands:
  setup-automation:
    steps:
      - run:
          name: Setup automation
          command: |
            apt-get update -qq
            apt-get install -y git openssh-client curl ca-certificates make tar gzip
            (mkdir -p deps; cd deps; git clone https://github.com/RedisLabsModules/readies.git)
            FORCE=1 VENV=1 ./deps/readies/bin/getpy3

  build-steps:
    parameters:
      coverage:
        type: boolean
        default: false 
    steps: 
      - checkout
      - setup-automation   
      - run:
          name: install dependencies
          command: |
            python3 -m virtualenv venv
            . venv/bin/activate
            python3 -m pip install -r test-requirements.txt
      - run:
          name: Run redis-server
          command: redis-server --loadmodule /usr/lib/redis/modules/redisai.so
          background: true
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            <<# parameters.coverage >>
            nosetests --with-coverage -vsx test
            codecov
            <</ parameters.coverage >>
            <<^ parameters.coverage >>
            nosetests -vsx test
            <</ parameters.coverage >>
      
jobs:
  build:
    docker:
      - image: redisfab/redisai:master-cpu-x64-bionic
    working_directory: ~/repo
    steps:
      - build-steps:
          coverage: true
      - store_artifacts:
          path: test-reports
          destination: test-reports

  build_nightly:
    docker:
      - image: redisfab/redisai:master-cpu-x64-bionic
    working_directory: ~/repo
    steps:
      - build-steps:
          coverage: false


workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_nightly
